config/routes.rb
Rails.application.routes.draw do

  

  resources :photos

  devise_for :passes
  root "homepage#index"

  get 'register'            => 'user#signUp',       :as=> 'register'
  post '/user/create'       => 'user#create'
  post '/user/user_sign_in' => 'user#user_sign_in', :as=> 'sign_in'
  get  'login'               => 'user#signIn',       :as=> 'login'
  get 'userpages/index'      => 'userpages#index',      :as=> 'userpages_path'
  get 'photos/'      => 'photos#index',      :as=> 'photos_path'
  get 'user/logout'     => 'user#logout', :as => 'logout'
   

end

app/models/pass.rb
class Pass < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable
	     
	belongs_to	:user
	validates	:user, 
				:presence=>{:message=>"No user specified"}

	validates	:email,
				:presence => {:message=>"No email entered"}

	validates	:password,
				:presence=>true,
				:confirmation =>true

	validates 	:password_confirmation, :presence=>true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :user
	# attr_accessible :photo_id,:title,:description,:image
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor 	:password, :password_confirmation
	after_save 		:save_pass
	before_save 	:set_pass

	has_one :pass
	has_many :photos, dependent: :destroy

	validates :first_name, 
	:presence=>{:message=>"Please enter your first name"}

	validates :last_name, 
	:presence=>{:message=>"Please enter your last name"}

	validates 	:username, 
	:presence=>{:message=>"Please enter your username"},
	:uniqueness=>{:message=>"Oops, Username already taken"}

	validates 	:email, 
	:presence=>{:message=>"Please enter email"},
	:format=>{ with: /\A[^@\s]+@([^@.\s]+\.)*[^@.\s]+\z/ },
	:uniqueness=>{:message=>"Oops, Email Address alreadsy in use"}

	validates	:password,
	:presence=>true,
	:confirmation =>true

	validates 	:password_confirmation, :presence=>true


	def set_pass
		@pass = Pass.new :email => self.email,
		:password => self.password,
		:password_confirmation => self.password_confirmation
	end

	def valid_password?(password)
		pass = Pass.find_by :user => self
		if pass.valid_password?(password)
			return true
		else
			return false				
		end
	end
    
	def fullname
		"#{first_name} #{last_name}"
	end

	private
		def save_pass
			@pass.user = self
			@pass.save
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  protected
  
  def check_pass!
    if pass_signed_in?
      redirect_to :user_path and return
    else
      return true
    end
  end

  def authenticate_pass!
    if pass_signed_in?
      super
    else
      flash[:notice] = "Please sign in to continue" 
      redirect_to :login and return
    end
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  layout 'homepage'
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  layout 'photo'
   respond_to :html, :xml, :json
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  
  def index
    user =session[:user_id]
    @photos = Photo.where(user_id: user)
    @photos = @photos.order("created_at DESC")
    respond_with(@photos)
  end

  def show
    
    respond_with(@photo)
  end

  def new
    @photo = Photo.new
    respond_with(@photo)
  end

  def edit
  end

  def create

    @user = User.find(params[:user_id])
    @photo = @user.photos.create(photo_params)
   if @photo.save
    respond_with(@photo)
   else
    render "new"
   end

  end

  def update
    @photo.update(photo_params)
    respond_with(@photo)
  end

  def destroy
    @photo.destroy
    respond_with(@photo)
  end

  private
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:title, :description, :image, :user_id)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    layout 'homepage'
	# before_action :check_pass!, :except=>:logout

	def logout
		sign_out :pass
		session[:user_id] = nil
		redirect_to :root
	end

	def user_sign_in
		params = user_params
		@user = User.find_by :email => params[:email]
		
		if @user
			if @user.valid_password?(params[:password])
				sign_in :pass, @user.pass
				session[:user_id] = @user.id
				redirect_to :photos_path and return
			else
				flash[:notice] = "Invalid password"	
			end	
		else
			flash[:notice] = "Invalid email or password"

		end
		@user = User.new :email => params[:email]

		render 'signIn'
	end

	def signUp
		@user = User.new
	end

	def signIn
		if !@user
			@user = User.new
		end
	end

	def create
		params = user_params

		@user = User.new user_params

		if @user.save
			flash[:notice] = "Get Started on pixhub Upload a picture now..."
			sign_in :pass, @user.pass
			redirect_to :photos_path and return
		else
			flash[:alert] = "Error occured #{@user.errors.messages}"
		end
		render 'signUp'
	end

	private

	def user_params
		allow = [:first_name, :last_name, :email, :username, :password, :password_confirmation]
		params.require(:user).permit(allow)
	end
end

app/controllers/userpages_controller.rb
class UserpagesController < ApplicationController
	layout 'application'
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/user_helper.rb
module UserHelper

end

app/helpers/userpages_helper.rb
module UserpagesHelper
end

app/views/homepage/index.html.erb
<div class="row" style= "margin-top:60px;"> 

	<div class="col-md-6">
		<h1 class="h1main" >STEP INTO THE SPOT LIGHT</h1><br>
		<h4 class="liststyle center"> With <span id="Focus">PIXhub</span> you can...</h4> 

		<span class=" glyphicon glyphicon-ok pull-left liststyle" style="text-align:left; ">Manage your pictures</span><br>
		<span class=" glyphicon glyphicon-ok pull-left liststyle" style="text-align:left; ">Uploads pictures to different social media platforms</span><br>
		<span class="glyphicon glyphicon-ok pull-left liststyle" style="text-align:left; ">See analytics on your pictures in SMPs</span><br>
		<span class=" glyphicon glyphicon-ok pull-left liststyle" style="text-align:left; ">Instantly take down unwanted pictures from SMPs</span>

		<div class="row pull-left" style="color:#E4F1FE;">
			<%= link_to "GET STARTED", :register, :class => "ctabtn btn btn-lg",:style => "color:#E4F1FE; font-size 30px;>" %>
		</div>

	</div>
	<div class="col-md-6">
		<img src="<%= asset_path( 'social.png' ) %>" width="600" height="600" alt="image error"/>	
	</div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pixhub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Pixhub" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, iE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <![endif]-->
      <%= stylesheet_link_tag params[:homepage] %>
      <%= stylesheet_link_tag "application", :media => "all" %>

      <!-- For third-generation iPad with high-resolution Retina display: -->
      <!-- Size should be 144 x 144 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

      <!-- For iPhone with high-resolution Retina display: -->
      <!-- Size should be 114 x 114 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

      <!-- For first- and second-generation iPad: -->
      <!-- Size should be 72 x 72 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

      <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
      <!-- Size should be 57 x 57 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

      <!-- For all other devices -->
      <!-- Size should be 32 x 32 pixels -->
      <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

      <%= javascript_include_tag "application" %>

      
    </head>
    <body id="homepage">



     <div class="navblock navbar-default shadow navbar-fixed-top">
       <div class="container ">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          
        <%= link_to "PixHub", :root , :class =>"navbar-brand" , :style => "font-size:40px; color:#E4F1FE ; font-family: 'Oswald', sans-serif;"%>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav pull-right navlinkstyle" style= "color:#E4F1FE;">

            <li><%= link_to "Sign In", :login ,:style => "color:#E4F1FE;" %></li>
            <li><%= link_to "Sign Up", :register ,:style => "color:#E4F1FE;"  %></li>
            <li><%= link_to "About", "",:style => "color:#E4F1FE;" %></li>
          </ul>
        </div>
      </div>
      </div>
        
          <div class="container">
                
              <%= yield %>
       
          <%= bootstrap_flash %>
          </div> <!-- /container -->
        






  </body>
  </html>

app/views/layouts/photo.html.erb
<!DOCTYPE HTML>
<html>
<head>
 <title>Pixhub | Home Page </title>
 <meta name="viewport" content="width=device-width,initial-scale=1">
 <link href='http://fonts.googleapis.com/css?family=Julius+Sans+One' rel='stylesheet' type='text/css'>
 <%= stylesheet_link_tag "application", :media => "all" %>

 <%= javascript_include_tag "application", :media => "all"%>
 
 <script>
  $(function() {
    var pull    = $('#pull');
    menu    = $('nav ul');
    menuHeight  = menu.height();

    $(pull).on('click', function(e) {
      e.preventDefault();
      menu.slideToggle();
    });

    $(window).resize(function(){
      var w = $(window).width();
      if(w > 320 && menu.is(':hidden')) {
        menu.removeAttr('style');
      }
    });
  });
</script>
</head>
<body>

 <div class="navuser navbar-default shadow navbar-fixed-top ">
   <div class="container ">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <%= link_to " PixHub", photos_path , :class =>"navbar-brand" , :style => "font-size:24px; color:#E4F1FE ; font-family: 'Oswald', sans-serif;"%>
     <%= link_to "Search", photos_path , :class =>"navbar-brand" , :style => "font-size:19px !important; color:#E4F1FE ; font-family: 'Oswald', sans-serif; margin-left:191px;"%>
    <div class="col-lg-3 " style="    padding-top: 2px;padding-left: 0px;margin-left: -7px;" >
            <div class="input-group custom-search-form">
              <input type="text" class="form-control" placeholder="Enter Title">
              <span class="input-group-btn">
              <button class="btn btn-default" type="button">
              <span class="glyphicon glyphicon-search"></span>
             </button>
             </span>
             </div><!-- /input-group -->
        </div>
 
    <div class="navbar-collapse collapse navbar-responsive-collapse">
     <ul class="nav navbar-nav navbar-right pull-right ">
      <li class="dropdown" style="left:45px;" >

       <%
       id=session[:user_id]
       u = User.find(id)
       %>
       <a href="#" style="padding-left:2px;" class=" navlinkstyleuser dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><%= u.fullname%><span class="caret"></span></a>
       <ul class="dropdown-menu" role="menu">
        <li><a href="#" style="padding-left:2px; font-family: sans-serif; color: #000;">Change Password</a></li>
        <l class="divider"></li>
        <li><%= link_to "Logout", :logout,:style => " padding-left:2px; font-family: sans-serif; color: #000;"%></li>
      </ul>
    </li>
  </ul>
  <ul class="nav navbar-nav navlinkstyleuser pull-right" style= "color:#E4F1FE;">
    <li><%= image_tag("home.png" , :title => "home", :class => "userimage") %></li>
    <li><%= link_to "Home",photos_path,:style => "color:#E4F1FE; padding-left:2px;" %></li>
    <li><%= image_tag("newpic.png" , :title => "Newpic", :class => "userimage") %></li>
    <li><%= link_to "New Photo", new_photo_path,:style => "color:#E4F1FE; padding-left:2px;" %></li>
    <li><%= image_tag("settings.png" , :title => "settings", :class => "userimage") %></li>
    <li><%= link_to "Settings", "",:style => "color:#E4F1FE; padding-left:2px;" %></li>
    <li style="left:45px;"><%= image_tag("user.png" , :title => "user", :class => "userimage") %></li>
  </ul>


</div>
</div>

</div>

<div id="container">
  <!---start-wrap---->

  <div id="main" role="main">
    <ul id="tiles"> 
    <ul class="lightGallery">
      
      <%= yield %>
    </ul>
    </ul>


    <footer>

    </footer>
  </div>

  <!-- include jQuery -->
<!--   <script src="js/jquery.min.js"></script>
-->
<!-- Include the imagesLoaded plug-in -->
<!--   <script src="js/jquery.imagesloaded.js"></script>
-->
<!-- Include the plug-in -->
<!--   <script src="js/jquery.wookmark.js"></script>
-->
<!-- Once the page is loaded, initalize the plug-in. -->
<script type="text/javascript">
  (function ($){
    $('#tiles').imagesLoaded(function() {
      var handler = null;

        // Prepare layout options.
        var options = {
          autoResize: true, // This will auto-update the layout when the browser window is resized.
          container: $('#main'), // Optional, used for some extra CSS styling
          offset: 20, // Optional, the distance between grid items
          itemWidth: 275 // Optional, the width of a grid item
        };

        /**
         * When scrolled all the way to the bottom, add more tiles.
         */
         function onScroll(event) {
          // Check if we're within 100 pixels of the bottom edge of the broser window.
          var winHeight = window.innerHeight ? window.innerHeight : $(window).height(); // iphone fix
          var closeToBottom = ($(window).scrollTop() + winHeight > $(document).height() - 100);

          if (closeToBottom) {
            // Get the first then items from the grid, clone them, and add them to the bottom of the grid.
            var items = $('#tiles li'),
            firstTen = items.slice(0, 10);
            $('#tiles').append(firstTen.clone());

            // Destroy the old handler
            if (handler.wookmarkInstance) {
              handler.wookmarkInstance.clear();
            }

            // Create a new layout handler.
            handler = $('#tiles li');
            handler.wookmark(options);
          }
        };

        // Capture scroll event.
        $(window).bind('scroll', onScroll);

        // Call the layout function.
        handler = $('#tiles li');
        handler.wookmark(options);
      });
})(jQuery);
</script>






</div>
</body>

</html>

app/views/photos/_form.html.erb
<div class="container">

 <div class="row">

  <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">

    <%= form_for @photo,:html => { :class => "form-horizontal formstyle",:multipart => true, :role => "form" } do |f| %>


    <% if @photo.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @photo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <% end %>
    
    <hr class="colorgraph">


    <div class="form-group">
      <%= f.text_field :title, :id => "title", :class => "form-control input-lg", :placeholder => "Title...in one word", :tabindex => "1"%>
    </div>

    <div class="form-group">
      <%= f.text_area :description, :id => "description", :class => "form-control input-lg", :placeholder => "Photo Description", :tabindex => "2"%>
    </div>

    <div class="form-group">
      <%= f.file_field :image, :id => "image", :class => "form-control input-lg", :tabindex => "3"%>
    </div>
    <% user= session[:user_id] %>

    <%= hidden_field_tag(:user_id, user) %>

    <hr class="colorgraph">

    <div class="row">
      <div class="col-xs-12 col-md-6">
        <%= f.submit :nil, {:class=>"btn btn-primary btn-block btn-lg",:tabindex => "4",:value => "Submit",data: { disable_with: "Please wait..."}, } %>
      </div>
      <div class="col-xs-12 col-md-6 offset-3">
     
       <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
       photos_path, :class => 'btn btn-default btn-block btn-lg' %>
     </div>

   </div>


   <% end %>
 </div>
</div>
</div>

app/views/photos/edit.html.erb
<%- model_class = Photo -%>
<div class="row" style="padding:7px; margin-top:0px;">
  <h1 id="Focus"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1> </div>

<%= render :partial => 'form' %>

app/views/photos/index.html.erb
<!-- These are our grid blocks -->
         <% @photos.each do |photo| %>
       

        <li data-src="<%= photo.image_url.to_s %>"  >
        <a href=""><%= image_tag photo.image_url.to_s%></a>
        <p><span class="pull-left" style="margin-top:2px;"><%= photo.title%></span><span><a href="<%=photo_path(photo)%>" style="padding:4px;"><span class="glyphicon glyphicon-eye-open"></span></a><a href="<%=edit_photo_path(photo)%>" class="dntshow"><span class="glyphicon glyphicon-pencil"></span></a><a href="<%=photo_path(photo)%>" class="dntshow"><span class="glyphicon glyphicon-th-list"></span></a><a href="<%=photo_path(photo)%>" class="dntshow"><span class="glyphicon glyphicon-share"></span></a></span></p></li>


        <%end%>
            </div>
   </div>

  
        <!-- End of grid blocks -->
    


<script type="text/javascript">
          $(document).ready(function() {
            $(".lightGallery").lightGallery(); 

          });
</script>

app/views/photos/new.html.erb
<%- model_class = Photo -%>

<%= render :partial => 'form' %>

app/views/photos/show.html.erb
<%- model_class = Photo -%>


<div class="container">
  <div class="row">
    <div class="col-md-6">

     <div class=" container-fluid imagedetails shadow">
     <%= image_tag @photo.image_url.to_s, :width => "353" , :class => "img img-responsive" %>
     </div>

   </div>
   <div class="col-md-6">
      <div class="panel panel-primary">
        <div class="panel-heading" id="Focus" style="height: 73px;
        text-align: initial; padding-top:5%; background-color:#2C3E50;">Photo Details
        </div>

        <div class="panel-body" style="background-color: #EEEEEE;">

              <div class="row">
                 <div class="col-md-4 labelstyle">
                   Photo Title    
                 </div>
                 <div class="col-md-8 contentstyle" >  
                  <%= @photo.title %>
                 </div>  
              </div>
              <br>
              <div class="row">
                  <div class="col-md-4 labelstyle">
                    Photo Description:
                  </div>
                  <div class="col-md-8 contentstyle" >  
                    <%= @photo.description %>
                  </div> 
              </div>
              <br>
              <div class="row">
                  <div class="col-md-4  labelstyle">
                    Created At:
                  </div>
                  <div class="col-md-8 contentstyle" >  
                   <%= @photo.created_at%>
                  </div> 
             </div>
             <br>
             <div class="row">
                  <div class="col-md-4  labelstyle">
                    Last Updated: 
                  </div>
                  <div class="col-md-8 contentstyle" >  
                   <%= @photo.updated_at%>
                 </div> 
             </div>
             <br>

          </div>
          <div class="panel-footer shadow" style="background-color:#2C3E50;">

            <%= link_to t('.back', :default => t("helpers.links.back")),
            photos_path, :class => 'btn btn-default'  %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_photo_path(@photo), :class => 'btn btn-default' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            photo_path(@photo),
            :method => 'delete',
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-danger' %>
          </div>


        </div>
      </div>

    </div>
</div>

app/views/user/signIn.html.erb
<div class="container">

       <div class="row" style="margin-top: 148px;">
                  <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                    <%= form_for @user,:html => { :class => "form-horizontal formstyle", :role => "form" }, :url => { :controller => :user, :action => :user_sign_in } do |f| %>
                  
                   <h2>Enter Login Details</h2>

                   <hr class="colorgraph">
                  <div class="form-group">
                    <%= f.text_field :email, :id => "email", :class => "form-control input-lg", :placeholder => "Email Address", :tabindex => "1"%>
                  </div> 
                 
                      <div class="form-group">
                        <%= f.password_field :password,required: true, :id => "password", :class => "form-control input-lg", :placeholder => "Password", :tabindex => "2" %>
                      </div>
                  
                 <hr class="colorgraph">
                 <div class="row">
                  <div class="col-xs-12 col-md-6">
                  </div>
                  <div class="col-xs-12 col-md-6 offset-3">
                   <%= f.submit :login, {:class=>"btn btn-primary btn-block btn-lg",:tabindex => "7",:value => "Submit",data: { disable_with: "Please wait..."}, } %>
                  </div>
                  
                </div>
                <% end %>
              </div>
       </div>
</div>

app/views/user/signUp.html.erb
<div class="container">

<div class="row" style="margin-top: 103px;">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
     <%=form_for @user,:html => { :class => "form-horizontal formstyle", :role => "form" },:url => { :controller => :user, :action => :create } do |f| %>

     <h2>Please Sign Up <small>It's free and always will be.</small></h2>
     <hr class="colorgraph">
     <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="form-group">
          <%= f.text_field :first_name,:id => "first_name",:class => "form-control input-lg",:placeholder => "First Name",:tabindex => "1" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="form-group">
            <%= f.text_field :last_name,:id => "last_name",:class => "form-control input-lg",:placeholder => "Last Name",:tabindex => "2" %>
        </div>
      </div>
    </div>
    <div class="form-group">
     <%= f.text_field :username,:id => "username",:class => "form-control input-lg",:placeholder => "Display Name",:tabindex => "3" %>
    </div>
    <div class="form-group">
      <%= f.text_field :email, :id => "email", :class => "form-control input-lg", :placeholder => "Email Address", :tabindex => "4"%>
    </div> 
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="form-group">
          <%= f.password_field :password,required: true, :id => "password", :class => "form-control input-lg", :placeholder => "Password", :tabindex => "5" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="form-group">
          <%= f.password_field :password_confirmation, required: true, :class => "form-control input-lg", :placeholder => "Confirm Password", :tabindex => "6"%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4 col-sm-3 col-md-3">
        <span class="button-checkbox">
          <button type="button" class="btn" data-color="info" tabindex="7">I Agree</button>
          <input type="checkbox" name="t_and_c" id="t_and_c" class="hidden" value="1">
        </span>
      </div>
      <div class="col-xs-8 col-sm-9 col-md-9">
       By clicking <strong class="label label-primary">Register</strong>, you agree to the <a href="#" data-toggle="modal" data-target="#t_and_c_m">Terms and Conditions</a> set out by this site, including our Cookie Use.
     </div>
   </div>

   <hr class="colorgraph">
   <div class="row">
    <div class="col-xs-12 col-md-6">
    </div>
    <div class="col-xs-12 col-md-6 offset-3">
     <%= f.submit :Register, {:class=>"btn btn-primary btn-block btn-lg",:tabindex => "7",:value => "Register",data: { disable_with: "Please wait..."}, } %>
    </div>
    
  </div>
  <% end %>
</div>
</div>





<!-- Modal -->
<div class="modal fade" id="t_and_c_m" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title" id="myModalLabel">Terms & Conditions</h4>
      </div>
      <div class="modal-body">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">I Agree</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</div>

app/views/userpages/index.html.erb
<h1>WELCOME TO YOUR HOME PAGE</h1>